# Generated by Django 6.0.2 on 2026-02-19 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reviews",
        ),
    ]
