# Generated by Django 6.0.2 on 2026-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
    ]
