# Generated by Django 6.0.2 on 2026-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/default-avatar.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
