# Generated by Django 6.0.2 on 2026-04-26 11:02

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введіть ім'я актора (наприклад: Тобі Магуайр)",
                        max_length=100,
                        unique=True,
                        verbose_name="Актор",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
            ],
            options={
                "verbose_name": "Актор",
                "verbose_name_plural": "Актори",
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введіть ім'я режисера фільму",
                        max_length=100,
                        unique=True,
                        verbose_name="Режисер",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
            ],
            options={
                "verbose_name": "Режисер",
                "verbose_name_plural": "Режисери",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введіть жанр фільму (наприклад: Драма, Жахи, Комедія)",
                        max_length=100,
                        unique=True,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанри",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-film", max_length=24, verbose_name="Іконка"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва категорії"
                    ),
                ),
                (
                    "singular_name",
                    models.CharField(max_length=100, verbose_name="Назва в однині"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
                (
                    "is_visible_on_home",
                    models.BooleanField(
                        default=True,
                        help_text="Виберіть, чи відображати цю категорію на головній сторінці",
                        verbose_name="Відображати на головній",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок відображення категорії на головній сторінці (менше значення — вище)",
                        verbose_name="Позиція",
                    ),
                ),
                (
                    "genres_in_filter",
                    models.ManyToManyField(
                        help_text="Виберіть жанри, які повинні бути видимими у фільтрі для цієї категорії",
                        to="movies.genre",
                        verbose_name="Жанри у фільтрі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Фільм (кілька дубляжів)"), (2, "Серіал (серії)")],
                        default=1,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Українська назва"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, verbose_name="URL-ім'я"
                    ),
                ),
                (
                    "en_title",
                    models.CharField(max_length=255, verbose_name="Англійська назва"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Тривалість фільму",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                (
                    "age_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                            ("G", "G (General Audiences)"),
                            ("PG", "PG (Parental Guidance Suggested)"),
                            ("PG-13", "PG-13 (Parents Strongly Cautioned)"),
                            ("R", "R (Restricted)"),
                            ("NC-17", "NC-17 (Adults Only)"),
                            ("TV-Y", "TV-Y (All Children)"),
                            ("TV-Y7", "TV-Y7 (Older Children)"),
                            ("TV-G", "TV-G (General Audience)"),
                            ("TV-PG", "TV-PG (Parental Guidance)"),
                            ("TV-14", "TV-14 (Parents Strongly Cautioned)"),
                            ("TV-MA", "TV-MA (Mature Audience)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Опис"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL зображення"
                    ),
                ),
                (
                    "trailer_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL-адреса трейлера"
                    ),
                ),
                (
                    "full_quality",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Якість"
                    ),
                ),
                ("imdb", models.FloatField(blank=True, null=True, verbose_name="IMDb")),
                (
                    "imdb_votes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Кількість голосів IMDB"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Рік випуску"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публікації",
                    ),
                ),
                (
                    "changed_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редагування"
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        help_text="Виберіть актора для цього фільму",
                        to="movies.actor",
                        verbose_name="Актори",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="movies",
                        to="movies.category",
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        help_text="Виберіть режисера для цього фільму",
                        to="movies.director",
                        verbose_name="Режисери",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        help_text="Виберіть жанр для цього фільму",
                        to="movies.genre",
                        verbose_name="Жанри",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фільм",
                "verbose_name_plural": "Фільми",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=256, verbose_name="Назва дубляжу"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="movies.movie",
                        verbose_name="Фільм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дубляж",
                "verbose_name_plural": "Дубляжі",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=300, verbose_name="URL")),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="URL-скріншот з фільму",
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер серії"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="movies.player",
                        verbose_name="Плеєр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Епізод",
                "verbose_name_plural": "Епізоди",
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screenshot_url",
                    models.URLField(verbose_name="URL Ha Кадр із фільму"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="movies.movie",
                        verbose_name="Фільм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кадри з фільму",
                "verbose_name_plural": "Кадри з фільмів",
            },
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=30, verbose_name="Мова / Назва субтитрів"
                    ),
                ),
                ("file", models.URLField(verbose_name="Файл субтитрів")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="movies.item",
                        verbose_name="Епізод",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субтитри для епізоду",
                "verbose_name_plural": "Субтитри для епізодів",
            },
        ),
    ]
