# Generated by Django 6.0.2 on 2026-02-19 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введіть ім'я актора (наприклад: Тобі Магуайр)",
                        max_length=100,
                        unique=True,
                        verbose_name="Актор",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
            ],
            options={
                "verbose_name": "Актор",
                "verbose_name_plural": "Актори",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введіть жанр фільму (наприклад: Драма, Жахи, Комедія)",
                        max_length=100,
                        unique=True,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанри",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-film", max_length=24, verbose_name="Іконка"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва категорії"
                    ),
                ),
                (
                    "singular_name",
                    models.CharField(max_length=100, verbose_name="Назва в однині"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
                    ),
                ),
                (
                    "is_visible_on_home",
                    models.BooleanField(
                        default=True,
                        help_text="Виберіть, чи відображати цю категорію на головній сторінці",
                        verbose_name="Відображати на головній",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок відображення категорії на головній сторінці (менше значення — вище)",
                        verbose_name="Позиція",
                    ),
                ),
                (
                    "genres_in_filter",
                    models.ManyToManyField(
                        help_text="Виберіть жанри, які повинні бути видимими у фільтрі для цієї категорії",
                        to="movies.genre",
                        verbose_name="Жанри у фільтрі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Фільм (кілька дубляжів)"), (2, "Серіал (серії)")],
                        default=1,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, verbose_name="URL-ім'я"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Опис"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL зображення"
                    ),
                ),
                (
                    "full_quality",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Якість"
                    ),
                ),
                ("imdb", models.FloatField(blank=True, null=True, verbose_name="IMDb")),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Рік випуску"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публікації",
                    ),
                ),
                (
                    "changed_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редагування"
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        help_text="Виберіть актора для цього фільму",
                        to="movies.actor",
                        verbose_name="Актори",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="movies",
                        to="movies.category",
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        help_text="Виберіть жанр для цього фільму",
                        to="movies.genre",
                        verbose_name="Жанри",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фільм",
                "verbose_name_plural": "Фільми",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=80, verbose_name="Назва дубляжу"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="movies.movie",
                        verbose_name="Фільм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дубляж",
                "verbose_name_plural": "Дубляжі",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=300, verbose_name="URL")),
                (
                    "episode_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер серії"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="movies.player",
                        verbose_name="Плеєр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Епізод",
                "verbose_name_plural": "Епізоди",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публікації",
                    ),
                ),
                (
                    "changed_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редагування"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="movies.movie",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="movies.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=30, verbose_name="Мова / Назва субтитрів"
                    ),
                ),
                ("file", models.URLField(verbose_name="Файл субтитрів")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="movies.item",
                        verbose_name="Епізод",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субтитри для епізоду",
                "verbose_name_plural": "Субтитри для епізодів",
            },
        ),
    ]
