# Generated by Django 6.0.2 on 2026-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="screenshot_url",
            field=models.URLField(max_length=500, verbose_name="URL Ha Кадр із фільму"),
        ),
    ]
