# Generated by Django 6.0.1 on 2026-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
