# Generated by Django 6.0.2 on 2026-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_screenshot_screenshot_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="en_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Англійська назва"
            ),
        ),
    ]
