# Generated by Django 6.0.1 on 2026-02-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_category_movie_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="fa-film", max_length=24),
        ),
    ]
