# Generated by Django 6.0.1 on 2026-02-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movies",
                to="movies.category",
            ),
        ),
    ]
