# Generated by Django 6.0.2 on 2026-03-18 19:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_movie_age_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
