# Generated by Django 6.0.1 on 2026-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_category_is_visible_on_home_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
