# Generated by Django 6.0.2 on 2026-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movie_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0+", "0+"),
                    ("6+", "6+"),
                    ("12+", "12+"),
                    ("16+", "16+"),
                    ("18+", "18+"),
                    ("G", "G (General Audiences)"),
                    ("PG", "PG (Parental Guidance Suggested)"),
                    ("PG-13", "PG-13 (Parents Strongly Cautioned)"),
                    ("R", "R (Restricted)"),
                    ("NC-17", "NC-17 (Adults Only)"),
                    ("TV-Y", "TV-Y (All Children)"),
                    ("TV-Y7", "TV-Y7 (Older Children)"),
                    ("TV-G", "TV-G (General Audience)"),
                    ("TV-PG", "TV-PG (Parental Guidance)"),
                    ("TV-14", "TV-14 (Parents Strongly Cautioned)"),
                    ("TV-MA", "TV-MA (Mature Audience)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
