# Generated by Django 6.0.1 on 2026-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_category_slug_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
