# Generated by Django 6.0.2 on 2026-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0010_alter_movie_age_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Тривалість фільму"
            ),
        ),
    ]
