# Generated by Django 6.0.1 on 2026-02-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0011_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="slug",
            field=models.SlugField(default="temp-slug", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(default="temp-slug", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movies",
                to="movies.category",
            ),
        ),
    ]
