# Generated by Django 6.0.2 on 2026-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_alter_player_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Назва дубляжу"),
        ),
    ]
