# Generated by Django 6.0.1 on 2026-02-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_actor_slug_genre_slug_alter_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
