# Generated by Django 6.0.2 on 2026-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_alter_player_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="poster_url",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="URL-скріншот з фільму",
            ),
        ),
    ]
