# Generated by Django 6.0.1 on 2026-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_alter_actor_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
