# Generated by Django 6.0.1 on 2026-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_alter_movie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Film (few dubs)"), (2, "Series (episodes)")], default=1
            ),
        ),
    ]
