# Generated by Django 6.0.1 on 2026-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0015_movie_movie_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(max_length=255),
        ),
    ]
