# Generated by Django 6.0.1 on 2026-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0016_alter_item_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(max_length=300),
        ),
    ]
