# Generated by Django 6.0.1 on 2026-02-14 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0017_alter_item_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name": "Актор", "verbose_name_plural": "Актори"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанри"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Епізод", "verbose_name_plural": "Епізоди"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Фільм", "verbose_name_plural": "Фільми"},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Дубляж", "verbose_name_plural": "Дубляжі"},
        ),
        migrations.AlterModelOptions(
            name="subtitle",
            options={
                "verbose_name": "Субтитри для епізоду",
                "verbose_name_plural": "Субтитри для епізодів",
            },
        ),
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(
                help_text="Введіть ім'я актора (наприклад: Тобі Магуайр)",
                max_length=100,
                unique=True,
                verbose_name="Актор",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="fa-film", max_length=24, verbose_name="Іконка"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_visible_on_home",
            field=models.BooleanField(
                default=True,
                help_text="Виберіть, чи відображати цю категорію на головній сторінці",
                verbose_name="Відображати на головній",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Назва категорії"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок відображення категорії на головній сторінці (менше значення — вище)",
                verbose_name="Позиція",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Введіть жанр фільму (наприклад: Драма, Жахи, Комедія)",
                max_length=100,
                unique=True,
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL-ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="episode_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер серії"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="movies.player",
                verbose_name="Плеєр",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(max_length=300, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                help_text="Виберіть актора для цього фільму",
                to="movies.actor",
                verbose_name="Актори",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movies",
                to="movies.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="changed_on",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата редагування"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публікації"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="full_quality",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Якість"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                help_text="Виберіть жанр для цього фільму",
                to="movies.genre",
                verbose_name="Жанри",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL зображення"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb",
            field=models.FloatField(blank=True, null=True, verbose_name="IMDb"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Фільм (кілька дубляжів)"), (2, "Серіал (серії)")],
                default=1,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Рік випуску"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="URL-ім'я"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="player",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="movies.movie",
                verbose_name="Фільм",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="title",
            field=models.CharField(max_length=80, verbose_name="Назва дубляжу"),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="file",
            field=models.URLField(verbose_name="Файл субтитрів"),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtitles",
                to="movies.item",
                verbose_name="Епізод",
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="label",
            field=models.CharField(
                max_length=30, verbose_name="Мова / Назва субтитрів"
            ),
        ),
    ]
