# Generated by Django 6.0.2 on 2026-04-13 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0017_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_user_movie_review",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
