# Generated by Django 6.0.1 on 2026-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0018_alter_actor_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="singular_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Назва в однині"
            ),
            preserve_default=False,
        ),
    ]
