# Generated by Django 6.0.1 on 2026-02-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_category_singular_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="genres_in_filter",
            field=models.ManyToManyField(
                help_text="Select  genres which should be visible in filter",
                to="movies.genre",
            ),
        ),
    ]
